<a href="https://colab.research.google.com/github/SiddhantMS/Statistics/blob/main/sudeep_bhargav_FileWork_day4_21_05_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

day4

In [ ]:
import os

os.chdir(r"/content/drive/MyDrive/stats")

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_excel("CDAC_DataBook.xlsx", sheet_name = 'ERPData')
print(df.head())

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [ ]:
grp1 = df.groupby('MaterialID')

In [ ]:
grp1.groups

{'AXCP-78': [1, 3, 4, 24, 25, 37, 38, 39, 46, 47, 48], 'DDBN-89': [22, 23, 26, 30, 40, 43, 45, 49], 'GCVB-79': [8, 15, 34, 35, 36], 'LXCV-21': [2, 27, 28, 29, 44], 'SDRT-67': [10, 11, 16, 17, 41, 42], 'TMI-43T': [0, 5, 6, 7, 9, 12, 13, 14, 18, 19, 20, 21, 31, 32, 33]}

In [ ]:
grp1.get_group('SDRT-67')

   MaterialID Location  Quantity
10    SDRT-67    MWH-1        34
11    SDRT-67    MWH-4        58
16    SDRT-67    MWH-5        12
17    SDRT-67    MWH-5       102
41    SDRT-67    MWH-1        57
42    SDRT-67    MWH-2        31

In [ ]:
grp1.Quantity.agg(np.sum)
grp1.Quantity.agg('sum')

/tmp/ipykernel_1053/1791751774.py:1: FutureWarning: The provided callable <function sum at 0x7a2493320860> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  grp1.Quantity.agg(np.sum)

MaterialID
AXCP-78    898
DDBN-89    383
GCVB-79    182
LXCV-21    243
SDRT-67    294
TMI-43T    885
Name: Quantity, dtype: int64

**grouping on two columns**

grouping willl always done on catogerical data

In [ ]:
grp1 = df.groupby(['Location','MaterialID'])
grp1

In [ ]:
type(grp1)

pandas.core.groupby.generic.DataFrameGroupBy

In [ ]:
grp1.groups

{('MWH-1', 'AXCP-78'): [1, 24, 25, 39, 48], ('MWH-1', 'DDBN-89'): [26, 40, 49], ('MWH-1', 'SDRT-67'): [10, 41], ('MWH-1', 'TMI-43T'): [9], ('MWH-2', 'AXCP-78'): [46], ('MWH-2', 'DDBN-89'): [45], ('MWH-2', 'GCVB-79'): [8, 15, 35, 36], ('MWH-2', 'LXCV-21'): [2], ('MWH-2', 'SDRT-67'): [42], ('MWH-2', 'TMI-43T'): [7], ('MWH-3', 'AXCP-78'): [47], ('MWH-3', 'DDBN-89'): [43], ('MWH-3', 'LXCV-21'): [44], ('MWH-3', 'TMI-43T'): [14], ('MWH-4', 'AXCP-78'): [4], ('MWH-4', 'DDBN-89'): [22, 30], ('MWH-4', 'SDRT-67'): [11], ('MWH-4', 'TMI-43T'): [0, 5, 6, 12, 13, 18, 19, 20, 21, 31, 32], ('MWH-5', 'AXCP-78'): [3, 37, 38], ('MWH-5', 'DDBN-89'): [23], ('MWH-5', 'GCVB-79'): [34], ('MWH-5', 'LXCV-21'): [27, 28, 29], ('MWH-5', 'SDRT-67'): [16, 17], ('MWH-5', 'TMI-43T'): [33]}

In [ ]:
#df.iloc[grp1.groups]
grp1.groups

{('MWH-1', 'AXCP-78'): [1, 24, 25, 39, 48], ('MWH-1', 'DDBN-89'): [26, 40, 49], ('MWH-1', 'SDRT-67'): [10, 41], ('MWH-1', 'TMI-43T'): [9], ('MWH-2', 'AXCP-78'): [46], ('MWH-2', 'DDBN-89'): [45], ('MWH-2', 'GCVB-79'): [8, 15, 35, 36], ('MWH-2', 'LXCV-21'): [2], ('MWH-2', 'SDRT-67'): [42], ('MWH-2', 'TMI-43T'): [7], ('MWH-3', 'AXCP-78'): [47], ('MWH-3', 'DDBN-89'): [43], ('MWH-3', 'LXCV-21'): [44], ('MWH-3', 'TMI-43T'): [14], ('MWH-4', 'AXCP-78'): [4], ('MWH-4', 'DDBN-89'): [22, 30], ('MWH-4', 'SDRT-67'): [11], ('MWH-4', 'TMI-43T'): [0, 5, 6, 12, 13, 18, 19, 20, 21, 31, 32], ('MWH-5', 'AXCP-78'): [3, 37, 38], ('MWH-5', 'DDBN-89'): [23], ('MWH-5', 'GCVB-79'): [34], ('MWH-5', 'LXCV-21'): [27, 28, 29], ('MWH-5', 'SDRT-67'): [16, 17], ('MWH-5', 'TMI-43T'): [33]}

In [ ]:
grp1.Quantity.agg('sum')

Location  MaterialID
MWH-1     AXCP-78       548
          DDBN-89       130
          SDRT-67        91
          TMI-43T       120
MWH-2     AXCP-78        85
          DDBN-89        69
          GCVB-79       156
          LXCV-21        27
          SDRT-67        31
          TMI-43T        29
MWH-3     AXCP-78        29
          DDBN-89        38
          LXCV-21        42
          TMI-43T        65
MWH-4     AXCP-78        36
          DDBN-89        75
          SDRT-67        58
          TMI-43T       559
MWH-5     AXCP-78       200
          DDBN-89        71
          GCVB-79        26
          LXCV-21       174
          SDRT-67       114
          TMI-43T       112
Name: Quantity, dtype: int64

In [ ]:
# go to parent df extract the same material i sum that you will get samae
sum(df.iloc[np.where((df.Location == 'MWH-1')&(df.MaterialID == 'AXCP-78'))].Quantity)

548

In [ ]:
grp1.Quantity.agg('sum')
newdf = grp1.Quantity.agg([np.sum,np.mean,np.size])
newdf

/tmp/ipykernel_1053/3364591395.py:2: FutureWarning: The provided callable <function sum at 0x7a2493320860> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  newdf = grp1.Quantity.agg([np.sum,np.mean,np.size])
/tmp/ipykernel_1053/3364591395.py:2: FutureWarning: The provided callable <function mean at 0x7a2493321940> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  newdf = grp1.Quantity.agg([np.sum,np.mean,np.size])

                     sum        mean  size
Location MaterialID
MWH-1    AXCP-78     548  109.600000     5
         DDBN-89     130   43.333333     3
         SDRT-67      91   45.500000     2
         TMI-43T     120  120.000000     1
MWH-2    AXCP-78      85   85.000000     1
         DDBN-89      69   69.000000     1
         GCVB-79     156   39.000000     4
         LXCV-21      27   27.000000     1
         SDRT-67      31   31.000000     1
         TMI-43T      29   29.000000     1
MWH-3    AXCP-78      29   29.000000     1
         DDBN-89      38   38.000000     1
         LXCV-21      42   42.000000     1
         TMI-43T      65   65.000000     1
MWH-4    AXCP-78      36   36.000000     1
         DDBN-89      75   37.500000     2
         SDRT-67      58   58.000000     1
         TMI-43T     559   50.818182    11
MWH-5    AXCP-78     200   66.666667     3
         DDBN-89      71   71.000000     1
         GCVB-79      26   26.000000     1
         LXCV-21     174   58.000000     3
         SDRT-67     114   57.000000     2
         TMI-43T     112  112.000000     1

In [ ]:
newdf.loc[['MWH-1','MWH-2']]

                     sum        mean  size
Location MaterialID
MWH-1    AXCP-78     548  109.600000     5
         DDBN-89     130   43.333333     3
         SDRT-67      91   45.500000     2
         TMI-43T     120  120.000000     1
MWH-2    AXCP-78      85   85.000000     1
         DDBN-89      69   69.000000     1
         GCVB-79     156   39.000000     4
         LXCV-21      27   27.000000     1
         SDRT-67      31   31.000000     1
         TMI-43T      29   29.000000     1


** **SORTING OF DATAFRAME** **


ASSENDING AND DECENDING SORTING OF DF

In [ ]:
df_sorted = df.sort_values('Quantity')  # in this .sort_values() sort values in assending order

In [ ]:
df_sorted.head()

   MaterialID Location  Quantity
8     GCVB-79    MWH-2        10
16    SDRT-67    MWH-5        12
34    GCVB-79    MWH-5        26
30    DDBN-89    MWH-4        27
2     LXCV-21    MWH-2        27

In [ ]:
df_sorted = df.sort_values('Quantity', ascending=False)  #now this is in desending order

In [ ]:
df_sorted = df.sort_values(['MaterialID','Location','Quantity'],ascending = False)
df_sorted

   MaterialID Location  Quantity
33    TMI-43T    MWH-5       112
5     TMI-43T    MWH-4        78
12    TMI-43T    MWH-4        76
21    TMI-43T    MWH-4        75
31    TMI-43T    MWH-4        65
19    TMI-43T    MWH-4        52
32    TMI-43T    MWH-4        43
20    TMI-43T    MWH-4        39
0     TMI-43T    MWH-4        34
18    TMI-43T    MWH-4        34
13    TMI-43T    MWH-4        32
6     TMI-43T    MWH-4        31
14    TMI-43T    MWH-3        65
7     TMI-43T    MWH-2        29
9     TMI-43T    MWH-1       120
17    SDRT-67    MWH-5       102
16    SDRT-67    MWH-5        12
11    SDRT-67    MWH-4        58
42    SDRT-67    MWH-2        31
41    SDRT-67    MWH-1        57
10    SDRT-67    MWH-1        34
27    LXCV-21    MWH-5        83
29    LXCV-21    MWH-5        57
28    LXCV-21    MWH-5        34
44    LXCV-21    MWH-3        42
2     LXCV-21    MWH-2        27
34    GCVB-79    MWH-5        26
15    GCVB-79    MWH-2        87
35    GCVB-79    MWH-2        31
36    GCVB-79    MWH-2        28
8     GCVB-79    MWH-2        10
23    DDBN-89    MWH-5        71
22    DDBN-89    MWH-4        48
30    DDBN-89    MWH-4        27
43    DDBN-89    MWH-3        38
45    DDBN-89    MWH-2        69
26    DDBN-89    MWH-1        57
49    DDBN-89    MWH-1        39
40    DDBN-89    MWH-1        34
38    AXCP-78    MWH-5        70
3     AXCP-78    MWH-5        65
37    AXCP-78    MWH-5        65
4     AXCP-78    MWH-4        36
47    AXCP-78    MWH-3        29
46    AXCP-78    MWH-2        85
24    AXCP-78    MWH-1       152
39    AXCP-78    MWH-1       145
25    AXCP-78    MWH-1       109
48    AXCP-78    MWH-1        75
1     AXCP-78    MWH-1        67

In [ ]:
df_sorted = df.sort_values(['MaterialID','Location','Quantity'],ascending = [True,False,True])
df_sorted

   MaterialID Location  Quantity
3     AXCP-78    MWH-5        65
37    AXCP-78    MWH-5        65
38    AXCP-78    MWH-5        70
4     AXCP-78    MWH-4        36
47    AXCP-78    MWH-3        29
46    AXCP-78    MWH-2        85
1     AXCP-78    MWH-1        67
48    AXCP-78    MWH-1        75
25    AXCP-78    MWH-1       109
39    AXCP-78    MWH-1       145
24    AXCP-78    MWH-1       152
23    DDBN-89    MWH-5        71
30    DDBN-89    MWH-4        27
22    DDBN-89    MWH-4        48
43    DDBN-89    MWH-3        38
45    DDBN-89    MWH-2        69
40    DDBN-89    MWH-1        34
49    DDBN-89    MWH-1        39
26    DDBN-89    MWH-1        57
34    GCVB-79    MWH-5        26
8     GCVB-79    MWH-2        10
36    GCVB-79    MWH-2        28
35    GCVB-79    MWH-2        31
15    GCVB-79    MWH-2        87
28    LXCV-21    MWH-5        34
29    LXCV-21    MWH-5        57
27    LXCV-21    MWH-5        83
44    LXCV-21    MWH-3        42
2     LXCV-21    MWH-2        27
16    SDRT-67    MWH-5        12
17    SDRT-67    MWH-5       102
11    SDRT-67    MWH-4        58
42    SDRT-67    MWH-2        31
10    SDRT-67    MWH-1        34
41    SDRT-67    MWH-1        57
33    TMI-43T    MWH-5       112
6     TMI-43T    MWH-4        31
13    TMI-43T    MWH-4        32
0     TMI-43T    MWH-4        34
18    TMI-43T    MWH-4        34
20    TMI-43T    MWH-4        39
32    TMI-43T    MWH-4        43
19    TMI-43T    MWH-4        52
31    TMI-43T    MWH-4        65
21    TMI-43T    MWH-4        75
12    TMI-43T    MWH-4        76
5     TMI-43T    MWH-4        78
14    TMI-43T    MWH-3        65
7     TMI-43T    MWH-2        29
9     TMI-43T    MWH-1       120

** Merging the data frame **\
we have pd.concat option but now we will do on pd.mearge()

In [ ]:
pune = pd.read_excel("CDAC_DataBook.xlsx",sheet_name='Pune')
mumbai = pd.read_excel("CDAC_DataBook.xlsx",sheet_name='Mumbai')

In [ ]:
pune

      Name      Subject Grade
0   Rakesh       Python     A
1    Manoj     MLPython     C
2  Vaibhav   Statistics     B
3   Hitesh   CommSkills     A
4   Suyash  ProjectMgmt     B
5    Vinod           AI     B

In [ ]:
mumbai

       Name     Subject Grade
0   Vaibhav   Six Sigma     A
1   Deepika  Statistics     B
2     Arjun  CommSkills     A
3    Chetan      Python     A
4  Abhishek    MLPython     B
5     Vinod          AI     C

In [ ]:
#there is no row and column  matching
# there is no person which have same naem sub grade
pd.merge(pune,mumbai) #we will get empty df but there is no any matching of common coln or row entire row should be common name subject and grade should be same

Empty DataFrame
Columns: [Name, Subject, Grade]
Index: []

In [ ]:
pd.merge(pune,mumbai,on='Subject')  #only common subject betn pune and mumbai will display

    Name_x     Subject Grade_x    Name_y Grade_y
0   Rakesh      Python       A    Chetan       A
1    Manoj    MLPython       C  Abhishek       B
2  Vaibhav  Statistics       B   Deepika       B
3   Hitesh  CommSkills       A     Arjun       A
4    Vinod          AI       B     Vinod       C

In [ ]:
pd.merge(pune,mumbai,on='Subject',how = 'inner')  #by default merger take as inner

    Name_x     Subject Grade_x    Name_y Grade_y
0   Rakesh      Python       A    Chetan       A
1    Manoj    MLPython       C  Abhishek       B
2  Vaibhav  Statistics       B   Deepika       B
3   Hitesh  CommSkills       A     Arjun       A
4    Vinod          AI       B     Vinod       C

In [ ]:
df1 = pd.merge(pune,mumbai,on='Subject',how = 'outer')
df1

    Name_x      Subject Grade_x    Name_y Grade_y
0    Vinod           AI       B     Vinod       C
1   Hitesh   CommSkills       A     Arjun       A
2    Manoj     MLPython       C  Abhishek       B
3   Suyash  ProjectMgmt       B       NaN     NaN
4   Rakesh       Python       A    Chetan       A
5      NaN    Six Sigma     NaN   Vaibhav       A
6  Vaibhav   Statistics       B   Deepika       B

In [ ]:
df1.iloc[np.where(df1.isnull())]

    Name_y Grade_y  Name_x Grade_x
3      NaN     NaN  Suyash       B
3      NaN     NaN  Suyash       B
5  Vaibhav       A     NaN     NaN
5  Vaibhav       A     NaN     NaN

In [ ]:
#df1.loc[np.where(df1.isnull())[0],('Name_y','Name_x','Grade_x','Grade_y')]=('User','user','X','Y')
df1

    Name_x      Subject Grade_x    Name_y Grade_y
0    Vinod           AI       B     Vinod       C
1   Hitesh   CommSkills       A     Arjun       A
2    Manoj     MLPython       C  Abhishek       B
3   Suyash  ProjectMgmt       B       NaN     NaN
4   Rakesh       Python       A    Chetan       A
5      NaN    Six Sigma     NaN   Vaibhav       A
6  Vaibhav   Statistics       B   Deepika       B