<a href="https://colab.research.google.com/github/SiddhantMS/Statistics/blob/main/sudeep_bhargav_Pandas_day2_19_05_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**DAY 2 - PANDAS**

In [ ]:
import numpy as np
import pandas as pd
from numpy import random
from numpy import linalg

In [ ]:
x1 = [4,8,4,3,2]

In [ ]:
type(x1)

list

In [ ]:
s1 = pd.Series(x1)
s1

0    4
1    8
2    4
3    3
4    2
dtype: int64

In [ ]:
s1 = pd.Series(x1, index = ['A','B','C','D','E'])
s1  # here we are define lable of our choice it is not index it is still 0,1,2,3.... this is different remember

A    4
B    8
C    4
D    3
E    2
dtype: int64

In [ ]:
s1.iloc[2]  # iloc  i stands for index and loc for location

np.int64(4)

In [ ]:
s1.loc['C'] # loc this is how we are getting from lable

np.int64(4)

In [ ]:
s1.iloc[[1,3]]
s1.loc[['C','D']]

C    4
D    3
dtype: int64

In [ ]:
s2 = pd.Series([1,2,3,4,5], index = ['A','A','B','A','B'])

# NOTE: you can have duplicat lables bur
# you cannnot have dublicate index

In [ ]:
s2.loc['A']

A    1
A    2
A    4
dtype: int64

In [ ]:
s2.iloc[3]

np.int64(4)

In [ ]:
s1

A    4
B    8
C    4
D    3
E    2
dtype: int64

In [ ]:
s3 = pd.Series([3,9], index=['F','G'])
s3

F    3
G    9
dtype: int64

In [ ]:
s1 = pd.concat([s1,s3])  # in this we have concat s1 and s3
s1

A    4
B    8
C    4
D    3
E    2
F    3
G    9
F    3
G    9
dtype: int64

In [ ]:
len(s1)
type(s1)

pandas.core.series.Series

In [ ]:
s1.loc['E'] = 9 # modify values based on lable

In [ ]:
s1.iloc[5] = 11 # modify values based on index

In [ ]:
s1

A     4
B     8
C     4
D     3
E     9
F    11
G     9
F     3
G     9
dtype: int64

In [ ]:
s2

A    1
A    2
B    3
A    4
B    5
dtype: int64

In [ ]:
s2.loc['A'] = 0

In [ ]:
s2

A    0
A    0
B    3
A    0
B    5
dtype: int64

In [ ]:
#delete the vlaues in series

s1

A     4
B     8
C     4
D     3
E     9
F    11
G     9
F     3
G     9
dtype: int64

In [ ]:
s1 = s1.drop(['E']) # delete the values of this lables

KeyError: "['E'] not found in axis"

In [ ]:
s1

A     4
B     8
C     4
D     3
F    11
G     9
F     3
G     9
dtype: int64

In [ ]:
s1.drop(s1.index[2])  # this time there is index 2 it will delete value form that index
# but here we havent assign to s1 so value is delete but not form origingal s1

A     4
B     8
D     3
F    11
G     9
F     3
G     9
dtype: int64

In [ ]:
s1

A     4
B     8
C     4
D     3
F    11
G     9
F     3
G     9
dtype: int64

In [ ]:
s4 = pd.Series([2,3,2,3,5,4,6,1,4,2,5,6,5,1,2,4,7,4,8,5,6,2,3,4,5,2])
s4.value_counts()  # this counts how many times the specific value get repeated

2    6
5    5
4    5
3    3
6    3
1    2
7    1
8    1
Name: count, dtype: int64

In [ ]:
s5 = s1.value_counts()
s5

4     2
3     2
9     2
8     1
11    1
Name: count, dtype: int64

In [ ]:
s5.loc[3]

np.int64(2)

In [ ]:
s5.iloc[4]

np.int64(1)

In [ ]:
#not knowing label not index only know value

s1.index[np.where(s1==9)[0]]
s1.index[np.where(s1==8)[0]]

Index(['B'], dtype='object')

DATA FRAMES

In [ ]:
mydata = [['A',1234,20000],['B',5678,10000],['C',9012,25000],['D',4456,70000]]

In [ ]:
mydata

[['A', 1234, 20000],
 ['B', 5678, 10000],
 ['C', 9012, 25000],
 ['D', 4456, 70000]]

In [ ]:
len(mydata)

4

In [ ]:
len(mydata[0])

3

In [ ]:
mydf = pd.DataFrame(mydata)

In [ ]:
mydf

   0     1      2
0  A  1234  20000
1  B  5678  10000
2  C  9012  25000
3  D  4456  70000

In [ ]:
mydf = pd.DataFrame(mydata, columns= ['Name','AccNO','Balance'])

In [ ]:
mydf

  Name  AccNO  Balance
0    A   1234    20000
1    B   5678    10000
2    C   9012    25000
3    D   4456    70000

In [ ]:
mydf = pd.DataFrame(mydata, columns= ['Name','AccNO','Balance'],index = [1,2,3,4])

In [ ]:
mydf

  Name  AccNO  Balance
1    A   1234    20000
2    B   5678    10000
3    C   9012    25000
4    D   4456    70000

In [ ]:
df1 = mydf.loc[[2,3,4]]
df1   # problem is here we also get the lables which are now not inproprate for this df

  Name  AccNO  Balance
2    B   5678    10000
3    C   9012    25000
4    D   4456    70000

In [ ]:
df1.loc[2]

Name           B
AccNO       5678
Balance    10000
Name: 2, dtype: object

In [ ]:
df1.iloc[2]

Name           D
AccNO       4456
Balance    70000
Name: 4, dtype: object

In [ ]:
#for fixing this lable problem
df1 = mydf.iloc[[1,2]].reset_index(drop = True) # thes ensure that the new lables should be start with 0

In [ ]:
df1

  Name  AccNO  Balance
0    B   5678    10000
1    C   9012    25000

In [ ]:
df1 = mydf.iloc[[1,2]].reset_index()  # in this we are reseting lables but the lable of last df will get one more add coloum as index
df1

   index Name  AccNO  Balance
0      2    B   5678    10000
1      3    C   9012    25000

if we have data for column wise then how we are working

In [ ]:
stu_info = {'Name':['A','B','C','D'], 'RollNO.':[1,2,3,4],'Marks':[50,60,75,64]}

In [ ]:
df1 =pd.DataFrame(stu_info)

In [ ]:
df1

  Name  RollNO.  Marks
0    A        1     50
1    B        2     60
2    C        3     75
3    D        4     64

In [ ]:
# if you want to add new rows to df the new df col. names should match

In [ ]:
newdf = pd.DataFrame([['E',7,35],['F',10,54]])
pd.concat([df1,newdf]) #here our column name are not matching so we have to give colon name when we are creating new df

  Name  RollNO.  Marks    0     1     2
0    A      1.0   50.0  NaN   NaN   NaN
1    B      2.0   60.0  NaN   NaN   NaN
2    C      3.0   75.0  NaN   NaN   NaN
3    D      4.0   64.0  NaN   NaN   NaN
0  NaN      NaN    NaN    E   7.0  35.0
1  NaN      NaN    NaN    F  10.0  54.0

In [ ]:
newdf = pd.DataFrame([['E',7,35],['F',10,54]], columns= df1.columns) #here we have given coln. name of df1 to new df
pd.concat([df1,newdf])
#now another problem occure of lables it is not in right position

  Name  RollNO.  Marks
0    A        1     50
1    B        2     60
2    C        3     75
3    D        4     64
0    E        7     35
1    F       10     54

In [ ]:
pd.concat([df1,newdf]).reset_index(drop=True)

  Name  RollNO.  Marks
0    A        1     50
1    B        2     60
2    C        3     75
3    D        4     64
4    E        7     35
5    F       10     54

now if we want ot add new colomn to this df

In [ ]:
df2 = pd.concat([df1,newdf]).reset_index(drop = True)
df2

  Name  RollNO.  Marks
0    A        1     50
1    B        2     60
2    C        3     75
3    D        4     64
4    E        7     35
5    F       10     54

In [ ]:
x1 = [67,89,75,62,59,82] #new colmn to add

In [ ]:
df2['Marks2'] = x1

In [ ]:
df2

  Name  RollNO.  Marks  Marks2
0    A        1     50      67
1    B        2     60      89
2    C        3     75      75
3    D        4     64      62
4    E        7     35      59
5    F       10     54      82

In [ ]:
#if we want to update some lable then
df2.at[3,'Marks']

np.int64(64)

In [ ]:
df2.at[3,'Marks'] = 74
df2

  Name  RollNO.  Marks  Marks2
0    A        1     50      67
1    B        2     60      89
2    C        3     75      75
3    D        4     74      62
4    E        7     35      59
5    F       10     54      82

In [ ]:
#if you want to updat by using the index
df2.iat[1,3]

np.int64(89)

In [ ]:
df2.iat[1,3]=99

In [ ]:
df2

  Name  RollNO.  Marks  Marks2
0    A        1     50      67
1    B        2     60      99
2    C        3     75      75
3    D        4     74      62
4    E        7     35      59
5    F       10     54      82

In [ ]:
#EXTRATING ROWS
df3 = df2.iloc([[2,3,4]])

TypeError: unhashable type: 'list'

In [ ]:
#Extract the colmns
mySubject = df2[['Name','Marks2']]

In [ ]:
mySubject

  Name  Marks2
0    A      67
1    B      99
2    C      75
3    D      62
4    E      59
5    F      82

In [ ]:
df2.iloc[:,[1,2]]  #when we dont know coln name and we want to get form the index

In [ ]:
# for only one coln need to be accessed
df2['Marks']
df2.Marks  #this is simple way

0    50
1    60
2    75
3    74
4    35
5    54
Name: Marks, dtype: int64

In [ ]:
#drop rows
df2.drop([1,4],axis=0)

  Name  RollNO.  Marks  Marks2
0    A        1     50      67
2    C        3     75      75
3    D        4     74      62
5    F       10     54      82

In [ ]:
#drop colmn
df2.drop('RollNO.',axis=1)

  Name  Marks  Marks2
0    A     50      67
1    B     60      99
2    C     75      75
3    D     74      62
4    E     35      59
5    F     54      82

In [ ]:
import os

In [ ]:
os.getcwd()

'/content'

In [ ]:
import os

os.chdir(r"/content/cdac")

In [ ]:
import pandas as pd

df = pd.read_excel("CDAC_DataBook.xlsx", sheet_name = 'ERPData')
print(df.head())

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36